"""empty message

Revision ID: c158e5ebe835
Revises: cda246d86b1d
Create Date: 2019-11-06 18:50:02.218985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c158e5ebe835'
down_revision = 'cda246d86b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'user_avatar')
    op.add_column('users', sa.Column('user_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_avatar')
    op.add_column('roles', sa.Column('user_avatar', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
