"""empty message

Revision ID: cda246d86b1d
Revises: 837b390159b6
Create Date: 2019-11-06 18:48:51.628988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda246d86b1d'
down_revision = '837b390159b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'user_avatar')
    # ### end Alembic commands ###
